version: '3'

services:
  nginx:
    image: nginx:1.25
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
    depends_on:
      - app1
      - app2

  app1:
    build: ./app1
    ports:
      - 50001:50001

  app2:
    build: ./app2
    ports:
      - 50002:50002
